name: cheezamapi
description: Cheezamapi is a non-official API of [Cheezam](https://www.cheezam.fr/) made using scraping.
version: 1.0.8
homepage: https://github.com/KikiManjaro/Cheezamapi

environment:
  sdk: '>=2.15.1 <3.0.0'
dev_dependencies:
  lints: ^1.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
dependencies:
  http: ^0.13.0
  json_annotation: ^4.4.0
  async: ^2.0.0
  path: ^1.6.0

assets:
  - assets/images/